# List Mode: The mode that the item types list will operate in
#   * Blacklist = Items added to the list will not be stackable
#   * Whitelist = Items added to the list will be stackable, but unstackable items will stay unstackable if they're not in the list
List Mode: Blacklist

# Item Types: Item types that will or will not be stacked to 64 based on the list mode above
Item Types:
  - Example Item

# Item Amounts: Set the amount of items that an item of that type can hold.
Item Amounts:
  Example Item: 64

# Default Max Amount: Set the default max amount for ALL items in Minecraft
# This setting could be dangerous, do proper testing before changing this value.
Default Max Amount: 64

# Hopper Movement Checks: Hoppers will attempt to stack unstackable items together.
# Setting this to false will stop hopper checks which could increase performance but will
# Stop stacking of unstackables when moving through hoppers.
Hopper Movement Checks: true

# Ground Stacking Checks: Simple Stack will check whether unstackable items on the ground
# will stack together or not.
# Setting this to false will stop unstackables stacking when on the ground and could
# increase performance at the cost of unstackables not stacking when on the ground.
Ground Stacking Checks: true

# Creative Item Dragging: When this is set to true, items that are dragged in a creative
# inventory will always become a full stack. This is a substitute for middle click dragging
# since middle click dragging can't be detected through the Spigot API.
Creative Item Dragging: false

simplestack:
  version: "Version: {VERSION}"
  commands:
    reload:
      success: "The config has been reloaded."
    reset:
      success: "The config has been reset to the default values."
    setamount:
      info: "Set the amount of a held item"
      success: "Amount set successfully."
      format: "Command format: /simplestack setamount <number>"
    additem:
      success: "The held item has been added to the config."
    removeitem:
      success: "The held item has been removed from the config."
  warnings:
    no_permission: "You do not have permission to use this command."
    must_be_player: "You must be a player to use this command."
    number_outside_of_range: "The amount specified for {MAT} is outside of the valid range. Defaulting to 64."
    invalid_material: "The material {MAT} in the config does not exist."
    invalid_unique_item: "An item listed in the unique items list could not be loaded."
    invalid_list_mode: "The list mode {MODE} is not a valid list mode. Defaulting to blacklist mode."
    invalid_max_amount: "The default max amount specified in the config is outside of the required range (1 - 64)"
    material_already_exists: "That material already exists in the config."
    custom_amount_does_not_exist: "A customized amount for that item type does not exist in the config."
    held_item_required: "You must hold an item to run this command."
  list_type:
    blacklist: "Blacklist"
    whitelist: "Whitelist"
